### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [curran/multiscale-timeseries#3]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by curran** [comment]
Sure! PRs welcome. I'm not familiar with how to add type declarations, but I'd welcome this if there's interest.

**Comment by geopic** [comment]
Excellent, I'll start on it now. It'll be no issue on your end, you'll just need to review and merge the PR when I'm done. :+1:
